# Generated by Django 5.2.3 on 2025-06-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcard',
            name='country',
            field=models.CharField(blank=True, default='UNKN', max_length=4),
        ),
    ]
